version: '3.8'

services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=HOST_IP
      - PASSWORD_HASH=BASE64_PW
      - WG_DEFAULT_DNS=10.2.0.2
    volumes:
      - ./wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    networks:
      vpn_network:
        ipv4_address: 10.2.0.10

  adguard:
    image: adguard/adguardhome
    container_name: adguard
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "000:3000/tcp"
    volumes:
      - ./adguard-data:/opt/adguardhome/work
      - ./adguard-config:/opt/adguardhome/conf
    restart: unless-stopped
    networks:
      vpn_network:
        ipv4_address: 10.2.0.2

networks:
  vpn_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/24

